name: Compile

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Compile the sketch
        run: arduino-cli compile --export-binaries --profile leonardo ./thermo

      - name: Save binaries
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: |
            ./**/*
            !./.git
          if-no-files-found: error
